"""Reference document generator for Package 122A architecture scans."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ashl_core_v1.tools.architecture_repo_scanner import canonical_json, load_scan_result


REFERENCE_DOC_NAMES = (
    "current_actual_module_map_v0.md",
    "ideal_end_state_module_map_v0.md",
    "ideal_vs_current_capability_matrix_v0.md",
    "architecture_interface_connection_map_v0.md",
    "architecture_bottleneck_and_gap_report_v0.md",
    "duplicate_or_orphan_module_report_v0.md",
    "roadmap_conflict_reconciliation_v0.md",
    "package_123_to_daily_runtime_revised_route_v0.md",
    "architecture_scan_baseline_v0.json",
)


def _header(title: str, scan: dict[str, Any]) -> str:
    baseline = scan.get("baseline", {})
    return (
        f"# {title}\n\n"
        "Status: Generated Reference\n"
        "Runtime Impact: None\n"
        "Generated By: Package 122A architecture reconciliation scanner\n"
        f"Source Scan: `{baseline.get('scan_id', 'unknown')}`\n"
        f"Scanned Commit: `{baseline.get('scanned_commit')}`\n\n"
    )


def _table(headers: tuple[str, ...], rows: list[tuple[Any, ...]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        out.append("| " + " | ".join(_cell(item) for item in row) + " |")
    return "\n".join(out) + "\n"


def _cell(value: Any) -> str:
    if isinstance(value, (tuple, list)):
        value = ", ".join(str(item) for item in value)
    if value is None:
        value = ""
    text = str(value).replace("\n", " ").replace("|", "\\|")
    return text if len(text) <= 180 else text[:177] + "..."


def _current_actual_module_map(scan: dict[str, Any]) -> str:
    rows = []
    for item in scan.get("analysis", {}).get("current_module_map", []):
        rows.append((item["organ"], item["module_ref"], item["current_status"], item["evidence"]))
    return _header("Current Actual Module Map v0", scan) + _table(
        ("Organ / Line", "Current Module Ref", "Current Status", "Evidence"),
        rows,
    )


def _ideal_end_state_module_map(scan: dict[str, Any]) -> str:
    rows = []
    for item in scan.get("analysis", {}).get("ideal_organs", []):
        rows.append(
            (
                item["organ_name"],
                item["purpose"],
                item["required_inputs"],
                item["required_outputs"],
                item["authority"],
                item["completion_milestone"],
            )
        )
    return _header("Ideal End State Module Map v0", scan) + _table(
        ("Organ", "Purpose", "Inputs", "Outputs", "Authority", "Completion Milestone"),
        rows,
    )


def _ideal_vs_current(scan: dict[str, Any]) -> str:
    current_by_name = {item["organ"].lower(): item for item in scan.get("analysis", {}).get("current_module_map", [])}
    gap_by_module = {}
    for gap in scan.get("analysis", {}).get("capability_gaps", []):
        gap_by_module.setdefault(gap["ideal_module"], []).append(gap)
    rows = []
    for ideal in scan.get("analysis", {}).get("ideal_organs", []):
        organ = ideal["organ_name"]
        current = current_by_name.get(organ.lower(), {})
        related_gaps = gap_by_module.get(organ, [])
        rows.append(
            (
                organ,
                ideal["purpose"],
                current.get("module_ref", ""),
                current.get("evidence", ""),
                current.get("current_status", "missing" if not current else current.get("current_status")),
                "; ".join(", ".join(gap["missing_interfaces"]) for gap in related_gaps),
                "; ".join(", ".join(gap["missing_runtime_behavior"]) for gap in related_gaps),
                "; ".join(", ".join(gap["blocks_package_ids"]) for gap in related_gaps),
                related_gaps[0]["recommended_resolution"] if related_gaps else "",
            )
        )
    return _header("Ideal Vs Current Capability Matrix v0", scan) + _table(
        (
            "Ideal organ",
            "Ideal capability",
            "Current implementation",
            "Current evidence",
            "Current status",
            "Missing interface",
            "Missing runtime behavior",
            "Blocks milestone",
            "Recommended package",
        ),
        rows,
    )


def _interface_map(scan: dict[str, Any]) -> str:
    rows = []
    for item in scan.get("interfaces", []):
        if item["connection_id"].startswith("architecture_interface_connection") and item["connection_status"] == "declared_but_not_implemented":
            continue
        rows.append(
            (
                item["connection_id"],
                item["source_module"],
                item["target_module"],
                item["connection_kind"],
                item["actual_import_exists"],
                item["actual_runtime_call_exists"],
                item["integration_test_exists"],
                item["connection_status"],
                item["risk_codes"],
            )
        )
    return _header("Architecture Interface Connection Map v0", scan) + _table(
        ("Connection", "Source", "Target", "Kind", "Import", "Call", "Test", "Status", "Risks"),
        rows,
    )


def _gap_report(scan: dict[str, Any]) -> str:
    out = _header("Architecture Bottleneck And Gap Report v0", scan)
    out += "## Bottlenecks\n\n"
    out += _table(
        ("Interface", "Status", "Info Loss", "Authority Risk", "Coupling Risk", "Action"),
        [
            (
                item["interface_name"],
                item["bottleneck_status"],
                item["information_loss_risk"],
                item["authority_concentration_risk"],
                item["coupling_risk"],
                item["recommended_action"],
            )
            for item in scan.get("analysis", {}).get("bottlenecks", [])
        ],
    )
    out += "\n## Gaps\n\n"
    out += _table(
        ("Gap", "Category", "Current", "Required", "Severity", "Blocks", "Resolution"),
        [
            (
                item["gap_name"],
                item["gap_category"],
                item["current_status"],
                item["required_status"],
                item["severity"],
                item["blocks_package_ids"],
                item["recommended_resolution"],
            )
            for item in scan.get("analysis", {}).get("capability_gaps", [])
        ],
    )
    return out


def _duplicates(scan: dict[str, Any]) -> str:
    return _header("Duplicate Or Orphan Module Report v0", scan) + _table(
        ("Item Kind", "Refs", "Classification", "Runtime Consumers", "Safe To Archive", "Human Review", "Reason"),
        [
            (
                item["item_kind"],
                item["item_refs"],
                item["classification"],
                item["current_runtime_consumer_count"],
                item["safe_to_archive"],
                item["requires_human_review"],
                item["reason"],
            )
            for item in scan.get("analysis", {}).get("duplicates_or_orphans", [])
        ],
    )


def _roadmap_conflicts(scan: dict[str, Any]) -> str:
    out = _header("Roadmap Conflict Reconciliation v0", scan)
    out += _table(
        ("Conflict", "Kind", "Packages", "Status", "Chosen Resolution", "Superseded Route Refs"),
        [
            (
                item["conflict_id"],
                item["conflict_kind"],
                item["conflicting_package_ids"],
                item["resolution_status"],
                item["chosen_resolution"],
                item["superseded_route_refs"],
            )
            for item in scan.get("roadmap", {}).get("roadmap_conflicts", [])
        ],
    )
    registry = scan.get("roadmap", {}).get("package_number_registry", {})
    out += "\n## Package Number Registry\n\n"
    out += "```json\n" + json.dumps(registry, indent=2, sort_keys=True) + "\n```\n"
    return out


def _route(scan: dict[str, Any]) -> str:
    return _header("Package 123 To Daily Runtime Revised Route v0", scan) + _table(
        ("Package", "Name", "Classification", "Milestone Dependency", "Route Note"),
        [
            (
                item["package_id"],
                item["package_name"],
                item["path_classification"],
                item["milestone_dependency"],
                item["route_note"],
            )
            for item in scan.get("roadmap", {}).get("revised_route", [])
        ],
    )


def generate_reference_docs(scan: dict[str, Any], docs_dir: str | Path) -> tuple[Path, ...]:
    output = Path(docs_dir)
    output.mkdir(parents=True, exist_ok=True)
    files = {
        "current_actual_module_map_v0.md": _current_actual_module_map(scan),
        "ideal_end_state_module_map_v0.md": _ideal_end_state_module_map(scan),
        "ideal_vs_current_capability_matrix_v0.md": _ideal_vs_current(scan),
        "architecture_interface_connection_map_v0.md": _interface_map(scan),
        "architecture_bottleneck_and_gap_report_v0.md": _gap_report(scan),
        "duplicate_or_orphan_module_report_v0.md": _duplicates(scan),
        "roadmap_conflict_reconciliation_v0.md": _roadmap_conflicts(scan),
        "package_123_to_daily_runtime_revised_route_v0.md": _route(scan),
    }
    written: list[Path] = []
    for name, content in files.items():
        path = output / name
        path.write_text(content, encoding="utf-8")
        written.append(path)
    baseline_path = output / "architecture_scan_baseline_v0.json"
    baseline_payload = {
        "baseline": scan.get("baseline", {}),
        "audit": scan.get("analysis", {}).get("audit", {}),
        "package_123_go_no_go": scan.get("analysis", {}).get("package_123_go_no_go", {}),
        "package_number_registry": scan.get("roadmap", {}).get("package_number_registry", {}),
        "source_scan_sha256": scan.get("scan_sha256"),
    }
    baseline_path.write_text(canonical_json(baseline_payload) + "\n", encoding="utf-8")
    written.append(baseline_path)
    return tuple(written)


def generate_reference_docs_from_scan_dir(scan_dir: str | Path, docs_dir: str | Path) -> tuple[Path, ...]:
    return generate_reference_docs(load_scan_result(scan_dir), docs_dir)
